name : Etude_TP
dependencies :
    - python>=3.8
    - pandas
    - jupyter
    - numpy
    - cython
    - pytest
    - pip
    - glpk
    - pip :
      - pyomo
      - dynprogstorage>=0.1.5
      - Mosek
      - xarray
      - plotly
      - matplotlib
      - sklearn

